# Generated by Django 5.0.4 on 2024-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.BooleanField(blank=True, help_text='female is False, male is True, null is unset', null=True, verbose_name='gender'),
        ),
    ]
